SELECT DISTINCT 'DELETE' "METADATA"
	, 'AssignmentGradeSteps' "AssignmentGradeSteps"
	, TO_CHAR(PAAM.ASSIGNMENT_ID) "AssignmentId"
	, TO_CHAR(PAGSF.ASSIGN_GRADE_STEP_ID) "AssignGradeStepId"
	, TO_CHAR(PAGSF.EFFECTIVE_START_DATE, 'YYYY/MM/DD') "EffectiveStartDate"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
	, PAPF.PERSON_NUMBER "PersonNumber(for reference only)" --for reference only
	, PAAM.ASSIGNMENT_NUMBER "AssignmentNumber"
	, PGSFT.NAME "GradeStepName"
	, PAB.ACTION_CODE "ActionCode(for reference only)"
FROM PER_ALL_PEOPLE_F PAPF
	, PER_ALL_ASSIGNMENTS_M PAAM
	, (PER_ASSIGN_GRADE_STEPS_F PAGSF
		LEFT JOIN PER_ACTION_OCCURRENCES PAO
		ON PAO.ACTION_OCCURRENCE_ID = PAGSF.ACTION_OCCURRENCE_ID)
			LEFT JOIN PER_ACTIONS_B PAB
			ON PAB.ACTION_ID = PAO.ACTION_ID
	, HRC_INTEGRATION_KEY_MAP HIKM
	, PER_GRADE_STEPS_F_TL PGSFT
WHERE 1 = 1
	AND PAPF.PERSON_ID = PAAM.PERSON_ID
	AND PAAM.ASSIGNMENT_ID = PAGSF.ASSIGNMENT_ID
	AND HIKM.SURROGATE_ID = PAGSF.ASSIGN_GRADE_STEP_ID
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PAGSF.EFFECTIVE_START_DATE AND PAGSF.EFFECTIVE_END_DATE
	AND PAAM.PRIMARY_FLAG = 'Y'
	AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
	AND PAAM.ASSIGNMENT_TYPE NOT LIKE '%T'
	AND PAAM.EFFECTIVE_START_DATE = (SELECT DISTINCT MAX(PAAM2.EFFECTIVE_START_DATE) FROM PER_ALL_ASSIGNMENTS_M PAAM2 WHERE PAAM2.PERSON_ID = PAAM.PERSON_ID)
	AND HIKM.OBJECT_NAME = 'AssignmentGradeStep'
	--AND PAPF.PERSON_NUMBER BETWEEN '00001226' AND '03003240'
	AND PGSFT.GRADE_STEP_ID = PAGSF.GRADE_STEP_ID
	AND PGSFT.LANGUAGE = PGSFT.SOURCE_LANG
ORDER BY PAPF.PERSON_NUMBER
