SELECT DISTINCT 'MERGE' "METADATA"
	, 'User' "User"
	, PAPF.PERSON_NUMBER "PersonNumber"
	, PPNF.DISPLAY_NAME "DisplayName"
	, PU.USERNAME "Username"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
	, PPNF.FIRST_NAME || '.' || PPNF.LAST_NAME "FirstName.LastName"
FROM PER_ALL_PEOPLE_F PAPF
	LEFT JOIN PER_USERS PU
	ON PAPF.PERSON_ID = PU.PERSON_ID
	, PER_PERSON_NAMES_F PPNF
	, HRC_INTEGRATION_KEY_MAP HIKM
WHERE 1 = 1
	AND HIKM.SURROGATE_ID = PU.USER_ID
	AND PAPF.PERSON_ID = PPNF.PERSON_ID
	AND PPNF.NAME_TYPE = 'GLOBAL'
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
	AND HIKM.OBJECT_NAME = 'User'
	AND PAPF.PERSON_NUMBER BETWEEN '00001226' AND '03003240'
	AND PU.USERNAME NOT LIKE (PPNF.FIRST_NAME || '.' || PPNF.LAST_NAME)
ORDER BY PAPF.PERSON_NUMBER
