SELECT DISTINCT 'MERGE' "METADATA"
	, 'WorkTerms' "WorkTerms"
	, PAPF.PERSON_NUMBER "PersonNumber"
	, PAAM.ASSIGNMENT_TYPE "AssignmentType"
	, PAAM.ASSIGNMENT_NUMBER "AssignmentNumber"
	, PAAM.EFFECTIVE_LATEST_CHANGE "EffectiveLatestChange"
	, TO_CHAR(PPOS.DATE_START, 'YYYY/MM/DD') "DateStart"
	, PPOS.PERIOD_TYPE "WorkerType"
	, HOUFT_LE.NAME "LegalEmployerName"
	, TO_CHAR(PAAM.EFFECTIVE_START_DATE, 'YYYY/MM/DD') "EffectiveStartDate"
	, TO_CHAR(PAAM.EFFECTIVE_END_DATE, 'YYYY/MM/DD') "EffectiveEndDate"
	, PAAM.EFFECTIVE_SEQUENCE "EffectiveSequence"
	, PAAM.ACTION_CODE "ActionCode"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
FROM PER_ALL_ASSIGNMENTS_M PAAM
	, PER_ALL_PEOPLE_F PAPF
	, PER_PERIODS_OF_SERVICE PPOS
	, HR_ORGANIZATION_UNITS_F_TL HOUFT_LE
	, HR_ORG_UNIT_CLASSIFICATIONS_F HOUCF_LE
	, HRC_INTEGRATION_KEY_MAP HIKM
WHERE 1 = 1
	AND PAAM.PERSON_ID = PAPF.PERSON_ID
	AND HIKM.SURROGATE_ID = PAAM.ASSIGNMENT_ID
	AND PAAM.ASSIGNMENT_TYPE LIKE '%T%'
	AND PAAM.EFFECTIVE_START_DATE = (SELECT MAX(PAAM2.EFFECTIVE_START_DATE)
										FROM PER_ALL_ASSIGNMENTS_M PAAM2
										WHERE 1 = 1
											AND PAAM2.PERSON_ID = PAAM.PERSON_ID)
	AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
	AND PPOS.PERSON_ID = PAPF.PERSON_ID
	AND PPOS.LEGAL_ENTITY_ID = HOUFT_LE.ORGANIZATION_ID
	AND HOUFT_LE.ORGANIZATION_ID = HOUCF_LE.ORGANIZATION_ID
	AND SYSDATE BETWEEN HOUFT_LE.EFFECTIVE_START_DATE AND HOUFT_LE.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN HOUCF_LE.EFFECTIVE_START_DATE AND HOUCF_LE.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND HIKM.OBJECT_NAME = 'Assignment'