SELECT DISTINCT 'MERGE' "METADATA"
	, 'WorkTerms' "WorkTerms"
	, PAAM.ASSIGNMENT_NUMBER "AssignmentNumber"
	, PAAM.EFFECTIVE_LATEST_CHANGE "EffectiveLatestChange"
	, PAPF.PERSON_NUMBER "PersonNumber"
	, TO_CHAR(PPOS.DATE_START, 'YYYY/MM/DD') "DateStart"
	, PPOS.PERIOD_TYPE "WorkerType"
	, HOUFT_LE.NAME "LegalEmployerName"
	, TO_CHAR(PAAM.EFFECTIVE_START_DATE, 'YYYY/MM/DD') "EffectiveStartDate"
	, TO_CHAR(PAAM.EFFECTIVE_END_DATE, 'YYYY/MM/DD') "EffectiveEndDate"
	, PAAM.EFFECTIVE_SEQUENCE "EffectiveSequence"
	, PAAM.ACTION_CODE "ActionCode"
	, PARB.ACTION_REASON_CODE "ReasonCode"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
FROM (PER_ALL_ASSIGNMENTS_M PAAM
	LEFT JOIN PER_ACTION_OCCURRENCES PAO
	ON PAO.ACTION_OCCURRENCE_ID = PAAM.ACTION_OCCURRENCE_ID)
		LEFT JOIN PER_ACTION_REASONS_B PARB
		ON PARB.ACTION_REASON_ID = PAO.ACTION_REASON_ID
	, PER_ALL_PEOPLE_F PAPF
	, PER_PERIODS_OF_SERVICE PPOS
	, HRC_INTEGRATION_KEY_MAP HIKM
	, HR_ORGANIZATION_UNITS_F_TL HOUFT_LE
WHERE 1 = 1
	AND HOUFT_LE.ORGANIZATION_ID = PPOS.LEGAL_ENTITY_ID
	AND HOUFT_LE.LANGUAGE = 'D'
	AND PAAM.PERSON_ID = PAPF.PERSON_ID
	AND HIKM.SURROGATE_ID = PAAM.ASSIGNMENT_ID
	AND PAAM.ASSIGNMENT_TYPE LIKE '%T%'
	AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
	AND PPOS.PERSON_ID = PAPF.PERSON_ID
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN HOUFT_LE.EFFECTIVE_START_DATE AND HOUFT_LE.EFFECTIVE_END_DATE
	AND PPOS.PRIMARY_FLAG = 'Y'
	AND HIKM.OBJECT_NAME = 'Assignment'
	AND PAPF.PERSON_NUMBER = NVL(:PersonNumber, PAPF.PERSON_NUMBER)
ORDER BY PAPF.PERSON_NUMBER, TO_CHAR(PAAM.EFFECTIVE_START_DATE, 'YYYY/MM/DD')
